import type { AdminDogRecord } from "./types";

export const mockAdminDogs: AdminDogRecord[] = [
  {
    id: "d-001",
    name: "Metsapolun Kide",
    sex: "FEMALE",
    birthDate: "2021-04-09",
    breederNameText: "Metsapolun",
    trialCount: 7,
    showCount: 4,
    ownershipPreview: ["Tiina Virtanen", "Antti Virtanen"],
    ekNo: 5588,
    note: "Tuotu admin-testiin. Tarkista sukutiedot ennen julkaisua.",
    registrationNo: "FI12345/21",
    sirePreview: {
      name: "Korven Aatos",
      registrationNo: "FI54321/20",
    },
    damPreview: {
      name: "Havupolun Helmi",
      registrationNo: "FI77777/18",
    },
  },
  {
    id: "d-002",
    name: "Korven Aatos",
    sex: "MALE",
    birthDate: "2020-11-21",
    breederNameText: "Korven",
    trialCount: 3,
    showCount: 9,
    ownershipPreview: ["Kari Nieminen"],
    ekNo: null,
    note: null,
    registrationNo: "FI54321/20",
    sirePreview: {
      name: "Lammen Riku",
      registrationNo: "FI31245/17",
    },
    damPreview: {
      name: "Saaren Aava",
      registrationNo: "FI11881/18",
    },
  },
  {
    id: "d-003",
    name: "Havupolun Helmi",
    sex: "UNKNOWN",
    birthDate: "2018-06-02",
    breederNameText: "Havupolun",
    trialCount: 0,
    showCount: 1,
    ownershipPreview: [],
    ekNo: 1020,
    note: "Sukupuolitieto puuttuu vanhasta datasta.",
    registrationNo: "FI77777/18",
    sirePreview: null,
    damPreview: null,
  },
];
