import {
  ShowWorkbookColumnDestinationKind,
  ShowWorkbookColumnParseMode,
  ShowWorkbookColumnPolicy,
  ShowWorkbookTargetField,
} from "@prisma/client";
import { prisma } from "../core/prisma";

type ShowWorkbookColumnSeed = {
  code: string;
  headerName: string;
  policy: ShowWorkbookColumnPolicy;
  destinationKind: ShowWorkbookColumnDestinationKind | null;
  targetField: ShowWorkbookTargetField | null;
  parseMode: ShowWorkbookColumnParseMode;
  fixedDefinitionCode: string | null;
  allowedDefinitionCategoryCode: string | null;
  headerRequired: boolean;
  rowValueRequired: boolean;
  sortOrder: number;
  valueMaps?: Array<{
    workbookValue: string;
    definitionCode: string;
    sortOrder?: number;
  }>;
};

const SHOW_WORKBOOK_COLUMN_RULES: ShowWorkbookColumnSeed[] = [
  {
    code: "REGISTRATION_NO",
    headerName: "Rekisterinumero",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_ENTRY,
    targetField: ShowWorkbookTargetField.REGISTRATION_NO,
    parseMode: ShowWorkbookColumnParseMode.TEXT,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: true,
    rowValueRequired: true,
    sortOrder: 10,
  },
  {
    code: "EVENT_DATE",
    headerName: "Aika",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_EVENT,
    targetField: ShowWorkbookTargetField.EVENT_DATE,
    parseMode: ShowWorkbookColumnParseMode.DATE,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: true,
    rowValueRequired: true,
    sortOrder: 20,
  },
  {
    code: "EVENT_CITY",
    headerName: "Paikkakunta",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_EVENT,
    targetField: ShowWorkbookTargetField.EVENT_CITY,
    parseMode: ShowWorkbookColumnParseMode.TEXT,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: true,
    rowValueRequired: true,
    sortOrder: 30,
  },
  {
    code: "EVENT_PLACE",
    headerName: "Paikka",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_EVENT,
    targetField: ShowWorkbookTargetField.EVENT_PLACE,
    parseMode: ShowWorkbookColumnParseMode.TEXT,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: true,
    rowValueRequired: true,
    sortOrder: 40,
  },
  {
    code: "EVENT_TYPE",
    headerName: "Näyttelytyyppi",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_EVENT,
    targetField: ShowWorkbookTargetField.EVENT_TYPE,
    parseMode: ShowWorkbookColumnParseMode.TEXT,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: true,
    rowValueRequired: true,
    sortOrder: 50,
  },
  {
    code: "DOG_NAME",
    headerName: "Nimi",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_ENTRY,
    targetField: ShowWorkbookTargetField.DOG_NAME,
    parseMode: ShowWorkbookColumnParseMode.TEXT,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: true,
    rowValueRequired: true,
    sortOrder: 60,
  },
  {
    code: "CLASS_VALUE",
    headerName: "Luokka",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: ShowWorkbookTargetField.CLASS_VALUE,
    parseMode: ShowWorkbookColumnParseMode.DEFINITION_FROM_CELL,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: "KILPAILULUOKKA",
    headerRequired: true,
    rowValueRequired: true,
    sortOrder: 70,
  },
  {
    code: "QUALITY_VALUE",
    headerName: "Laatuarvostelu",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: ShowWorkbookTargetField.QUALITY_VALUE,
    parseMode: ShowWorkbookColumnParseMode.DEFINITION_FROM_CELL,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: "LAATUARVOSTELU",
    headerRequired: true,
    rowValueRequired: true,
    sortOrder: 80,
  },
  {
    code: "BREED_CODE",
    headerName: "Rotukoodi",
    policy: ShowWorkbookColumnPolicy.IGNORE,
    destinationKind: null,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.TEXT,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 90,
  },
  {
    code: "PLACEMENT",
    headerName: "Sijoitus",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.FIXED_NUMERIC,
    fixedDefinitionCode: "SIJOITUS",
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 100,
  },
  {
    code: "PUPN",
    headerName: "PuPn",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.FIXED_CODE,
    fixedDefinitionCode: "PUPN",
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 110,
  },
  {
    code: "BREED_RANKING",
    headerName: "ROP",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.VALUE_MAP,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 120,
    valueMaps: [
      { workbookValue: "ROP", definitionCode: "ROP", sortOrder: 10 },
      { workbookValue: "VSP", definitionCode: "VSP", sortOrder: 20 },
    ],
  },
  {
    code: "CERT",
    headerName: "SERT",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.VALUE_MAP,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 130,
    valueMaps: [
      { workbookValue: "SERT", definitionCode: "SERT", sortOrder: 10 },
      { workbookValue: "varaSERT", definitionCode: "varaSERT", sortOrder: 20 },
    ],
  },
  {
    code: "NORD_CERT",
    headerName: "NORD-SERT",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.VALUE_MAP,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 140,
    valueMaps: [
      {
        workbookValue: "NORD-SERT",
        definitionCode: "NORD-SERT",
        sortOrder: 10,
      },
      {
        workbookValue: "NORD-varaSERT",
        definitionCode: "NORD-varaSERT",
        sortOrder: 20,
      },
    ],
  },
  {
    code: "JUN_CERT",
    headerName: "JUN-SERT",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.FIXED_FLAG,
    fixedDefinitionCode: "JUN-SERT",
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 150,
  },
  {
    code: "VET_CERT",
    headerName: "VET-SERT",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.FIXED_FLAG,
    fixedDefinitionCode: "VET-SERT",
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 160,
  },
  {
    code: "CHAMPION",
    headerName: "MVA",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.FIXED_FLAG,
    fixedDefinitionCode: "MVA",
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 170,
  },
  {
    code: "JUN_CHAMPION",
    headerName: "JMVA",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.FIXED_FLAG,
    fixedDefinitionCode: "JMVA",
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 180,
  },
  {
    code: "VET_CHAMPION",
    headerName: "VMVA",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.FIXED_FLAG,
    fixedDefinitionCode: "VMVA",
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 190,
  },
  {
    code: "CACIB",
    headerName: "CACIB",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.VALUE_MAP,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 200,
    valueMaps: [
      { workbookValue: "CACIB", definitionCode: "CACIB", sortOrder: 10 },
      {
        workbookValue: "varaCACIB",
        definitionCode: "varaCACIB",
        sortOrder: 20,
      },
    ],
  },
  {
    code: "CACIB_J",
    headerName: "CACIB-J",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.FIXED_FLAG,
    fixedDefinitionCode: "CACIB-J",
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 210,
  },
  {
    code: "CACIB_V",
    headerName: "CACIB-V",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.FIXED_FLAG,
    fixedDefinitionCode: "CACIB-V",
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 220,
  },
  {
    code: "VET_BREED_RANKING",
    headerName: "VET-ROP",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.VALUE_MAP,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 230,
    valueMaps: [
      { workbookValue: "VET-ROP", definitionCode: "VET-ROP", sortOrder: 10 },
      { workbookValue: "VET-VSP", definitionCode: "VET-VSP", sortOrder: 20 },
    ],
  },
  {
    code: "JUN_BREED_RANKING",
    headerName: "JUN-ROP",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.VALUE_MAP,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 240,
    valueMaps: [
      { workbookValue: "JUN-ROP", definitionCode: "JUN-ROP", sortOrder: 10 },
      { workbookValue: "JUN-VSP", definitionCode: "JUN-VSP", sortOrder: 20 },
    ],
  },
  {
    code: "SA",
    headerName: "SA",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.FIXED_FLAG,
    fixedDefinitionCode: "SA",
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 250,
  },
  {
    code: "KP",
    headerName: "KP",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_RESULT_ITEM,
    targetField: null,
    parseMode: ShowWorkbookColumnParseMode.FIXED_FLAG,
    fixedDefinitionCode: "KP",
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 260,
  },
  {
    code: "JUDGE",
    headerName: "Tuomari",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_ENTRY,
    targetField: ShowWorkbookTargetField.JUDGE,
    parseMode: ShowWorkbookColumnParseMode.TEXT,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 270,
  },
  {
    code: "CRITIQUE_TEXT",
    headerName: "Arvostelu",
    policy: ShowWorkbookColumnPolicy.IMPORT,
    destinationKind: ShowWorkbookColumnDestinationKind.SHOW_ENTRY,
    targetField: ShowWorkbookTargetField.CRITIQUE_TEXT,
    parseMode: ShowWorkbookColumnParseMode.TEXT,
    fixedDefinitionCode: null,
    allowedDefinitionCategoryCode: null,
    headerRequired: false,
    rowValueRequired: false,
    sortOrder: 280,
  },
];

export async function seedShowWorkbookImportSchema(): Promise<{
  upserted: number;
}> {
  let upserted = 0;

  for (const rule of SHOW_WORKBOOK_COLUMN_RULES) {
    const row = await prisma.showWorkbookColumnRule.upsert({
      where: { code: rule.code },
      create: {
        code: rule.code,
        headerName: rule.headerName,
        policy: rule.policy,
        destinationKind: rule.destinationKind,
        targetField: rule.targetField,
        parseMode: rule.parseMode,
        fixedDefinitionCode: rule.fixedDefinitionCode,
        allowedDefinitionCategoryCode: rule.allowedDefinitionCategoryCode,
        headerRequired: rule.headerRequired,
        rowValueRequired: rule.rowValueRequired,
        sortOrder: rule.sortOrder,
        isEnabled: true,
      },
      update: {
        headerName: rule.headerName,
        policy: rule.policy,
        destinationKind: rule.destinationKind,
        targetField: rule.targetField,
        parseMode: rule.parseMode,
        fixedDefinitionCode: rule.fixedDefinitionCode,
        allowedDefinitionCategoryCode: rule.allowedDefinitionCategoryCode,
        headerRequired: rule.headerRequired,
        rowValueRequired: rule.rowValueRequired,
        sortOrder: rule.sortOrder,
        isEnabled: true,
      },
      select: { id: true },
    });

    await prisma.showWorkbookColumnValueMap.deleteMany({
      where: { ruleId: row.id },
    });

    if ((rule.valueMaps?.length ?? 0) > 0) {
      await prisma.showWorkbookColumnValueMap.createMany({
        data: rule.valueMaps!.map((valueMap, index) => ({
          ruleId: row.id,
          workbookValue: valueMap.workbookValue,
          definitionCode: valueMap.definitionCode,
          sortOrder: valueMap.sortOrder ?? index,
        })),
      });
    }

    upserted += 1;
  }

  return { upserted };
}
