-- Add frozen legacy trial mirror tables for source validation and later projection.

-- AlterEnum
ALTER TYPE "ImportKind" RENAME VALUE 'LEGACY_PHASE2' TO 'LEGACY_TRIAL_MIRROR';

-- CreateTable
CREATE TABLE "legacy_akoeall" (
    "REKNO" VARCHAR(20) NOT NULL,
    "TAPPA" VARCHAR(50) NOT NULL,
    "TAPPV" VARCHAR(8) NOT NULL,
    "KENNELPIIRI" VARCHAR(50),
    "KENNELPIIRINRO" CHAR(3),
    "KE" CHAR(1),
    "LK" CHAR(1),
    "PA" CHAR(1),
    "PISTE" DECIMAL(6,2),
    "SIJA" VARCHAR(5),
    "HAKU" DECIMAL(6,2),
    "HAUK" DECIMAL(6,2),
    "YVA" DECIMAL(6,2),
    "HLO" DECIMAL(6,2),
    "ALO" DECIMAL(6,2),
    "TJA" DECIMAL(6,2),
    "PIN" DECIMAL(6,2),
    "TUOM1" VARCHAR(20),
    "MUOKATTU" VARCHAR(19) NOT NULL,
    "VARA" CHAR(3),
    "raw_payload_json" TEXT NOT NULL,
    "source_hash" VARCHAR(64),
    "imported_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "legacy_akoeall_pkey" PRIMARY KEY ("REKNO","TAPPA","TAPPV")
);

-- CreateTable
CREATE TABLE "legacy_bealt" (
    "REKNO" VARCHAR(20) NOT NULL,
    "TAPPA" VARCHAR(20) NOT NULL,
    "TAPPV" VARCHAR(8) NOT NULL,
    "ERA" SMALLINT NOT NULL,
    "HAKUMIN" SMALLINT,
    "AJOMIN" SMALLINT,
    "HAKU" DECIMAL(6,2),
    "HAUK" DECIMAL(6,2),
    "YVA" DECIMAL(6,2),
    "HLO" DECIMAL(6,2),
    "ALO" DECIMAL(6,2),
    "TJA" DECIMAL(6,2),
    "PIN" DECIMAL(6,2),
    "LT11" CHAR(1),
    "LT12" SMALLINT,
    "LT13" CHAR(1),
    "LT14" CHAR(1),
    "LT15" CHAR(1),
    "LT16" CHAR(1),
    "LT17" VARCHAR(5),
    "LT18" DECIMAL(3,1),
    "LT20" DECIMAL(3,1),
    "LT21" DECIMAL(3,1),
    "LT30" DECIMAL(3,1),
    "LT31" DECIMAL(3,1),
    "LT32" DECIMAL(3,1),
    "LT33" DECIMAL(3,1),
    "LT34" DECIMAL(3,1),
    "LT40" DECIMAL(3,1),
    "LT41" DECIMAL(3,1),
    "LT42" DECIMAL(3,1),
    "LT43" DECIMAL(3,1),
    "LT44" DECIMAL(3,1),
    "LT50" DECIMAL(3,1),
    "LT51" DECIMAL(3,1),
    "LT52" DECIMAL(3,1),
    "LT53" DECIMAL(3,1),
    "VIITE" VARCHAR(255),
    "MUOKATTU" VARCHAR(19) NOT NULL,
    "raw_payload_json" TEXT NOT NULL,
    "source_hash" VARCHAR(64),
    "imported_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "legacy_bealt_pkey" PRIMARY KEY ("REKNO","TAPPA","TAPPV","ERA")
);

-- CreateTable
CREATE TABLE "legacy_bealt0" (
    "REKNO" VARCHAR(20) NOT NULL,
    "TAPPA" VARCHAR(20) NOT NULL,
    "TAPPV" VARCHAR(8) NOT NULL,
    "ERA" SMALLINT NOT NULL,
    "ALKOI" VARCHAR(5),
    "HAKUMIN" SMALLINT,
    "AJOMIN" SMALLINT,
    "HAKU" DECIMAL(6,2),
    "HAUK" DECIMAL(6,2),
    "YVA" DECIMAL(6,2),
    "HLO" DECIMAL(6,2),
    "ALO" DECIMAL(6,2),
    "TJA" DECIMAL(6,2),
    "PIN" DECIMAL(6,2),
    "LT11" DECIMAL(3,1),
    "LT12" DECIMAL(3,1),
    "LT13" DECIMAL(3,1),
    "LT21" DECIMAL(3,1),
    "LT22" DECIMAL(3,1),
    "LT31" DECIMAL(3,1),
    "LT32" DECIMAL(3,1),
    "LT33" DECIMAL(3,1),
    "LT34" DECIMAL(3,1),
    "LT41" DECIMAL(3,1),
    "LT42" DECIMAL(3,1),
    "LT43" DECIMAL(3,1),
    "LT44" DECIMAL(3,1),
    "LT51" DECIMAL(3,1),
    "LT52" DECIMAL(3,1),
    "LT61" DECIMAL(3,1),
    "LT62" DECIMAL(3,1),
    "LT63" DECIMAL(3,1),
    "LT64" DECIMAL(3,1),
    "LT65" DECIMAL(3,1),
    "LT66" DECIMAL(3,1),
    "LT71" DECIMAL(3,1),
    "LT72" DECIMAL(3,1),
    "LT73" DECIMAL(3,1),
    "LT74" DECIMAL(3,1),
    "LT75" DECIMAL(3,1),
    "LT76" DECIMAL(3,1),
    "LT77" DECIMAL(3,1),
    "LT78" DECIMAL(3,1),
    "LT79" DECIMAL(3,1),
    "LT80" DECIMAL(3,1),
    "LT81" DECIMAL(3,1),
    "VIITE" VARCHAR(255),
    "MUOKATTU" VARCHAR(19) NOT NULL,
    "raw_payload_json" TEXT NOT NULL,
    "source_hash" VARCHAR(64),
    "imported_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "legacy_bealt0_pkey" PRIMARY KEY ("REKNO","TAPPA","TAPPV","ERA")
);

-- CreateTable
CREATE TABLE "legacy_bealt1" (
    "REKNO" VARCHAR(20) NOT NULL,
    "TAPPA" VARCHAR(20) NOT NULL,
    "TAPPV" VARCHAR(8) NOT NULL,
    "ERA" SMALLINT NOT NULL,
    "ALKOI" VARCHAR(5),
    "HAKUMIN" SMALLINT,
    "AJOMIN" SMALLINT,
    "HAKU" DECIMAL(6,2),
    "HAUK" DECIMAL(6,2),
    "YVA" DECIMAL(6,2),
    "HLO" DECIMAL(6,2),
    "ALO" DECIMAL(6,2),
    "TJA" DECIMAL(6,2),
    "PIN" DECIMAL(6,2),
    "LT11" CHAR(1),
    "LT12" SMALLINT,
    "LT13" CHAR(1),
    "LT14" CHAR(1),
    "LT15" CHAR(1),
    "LT16" CHAR(1),
    "LT17" VARCHAR(5),
    "LT18" DECIMAL(3,1),
    "LT20" DECIMAL(3,1),
    "LT21" DECIMAL(3,1),
    "LT30" DECIMAL(3,1),
    "LT31" DECIMAL(3,1),
    "LT32" DECIMAL(3,1),
    "LT33" DECIMAL(3,1),
    "LT34" DECIMAL(3,1),
    "LT40" DECIMAL(3,1),
    "LT41" DECIMAL(3,1),
    "LT42" DECIMAL(3,1),
    "LT43" DECIMAL(3,1),
    "LT44" DECIMAL(3,1),
    "LT50" DECIMAL(3,1),
    "LT51" DECIMAL(3,1),
    "LT52" DECIMAL(3,1),
    "LT53" DECIMAL(3,1),
    "VIITE" VARCHAR(255),
    "MUOKATTU" VARCHAR(19) NOT NULL,
    "raw_payload_json" TEXT NOT NULL,
    "source_hash" VARCHAR(64),
    "imported_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "legacy_bealt1_pkey" PRIMARY KEY ("REKNO","TAPPA","TAPPV","ERA")
);

-- CreateTable
CREATE TABLE "legacy_bealt2" (
    "REKNO" VARCHAR(20) NOT NULL,
    "TAPPA" VARCHAR(50) NOT NULL,
    "TAPPV" VARCHAR(8) NOT NULL,
    "ERA" SMALLINT NOT NULL,
    "ALKOI" VARCHAR(5),
    "HAKUMIN" SMALLINT,
    "AJOMIN" SMALLINT,
    "HAKU" DECIMAL(6,2),
    "HAUK" DECIMAL(6,2),
    "YVA" DECIMAL(6,2),
    "HLO" DECIMAL(6,2),
    "ALO" DECIMAL(6,2),
    "TJA" DECIMAL(6,2),
    "PIN" DECIMAL(6,2),
    "LT11" CHAR(1),
    "LT12" SMALLINT,
    "LT13" CHAR(1),
    "LT14" CHAR(1),
    "LT15" CHAR(1),
    "LT16" CHAR(1),
    "LT17" VARCHAR(5),
    "LT18" DECIMAL(3,1),
    "LT20" DECIMAL(3,1),
    "LT21" DECIMAL(3,1),
    "LT22" DECIMAL(3,1),
    "LT30" DECIMAL(3,1),
    "LT31" DECIMAL(3,1),
    "LT32" DECIMAL(3,1),
    "LT33" DECIMAL(3,1),
    "LT34" DECIMAL(3,1),
    "LT35" DECIMAL(3,1),
    "LT36" DECIMAL(3,1),
    "LT40" DECIMAL(3,1),
    "LT41" DECIMAL(3,1),
    "LT50" DECIMAL(3,1),
    "LT51" DECIMAL(3,1),
    "LT52" DECIMAL(3,1),
    "LT53" DECIMAL(3,1),
    "LT54" DECIMAL(3,1),
    "LT55" DECIMAL(3,1),
    "LT56" DECIMAL(3,1),
    "LT60" DECIMAL(3,1),
    "LT61" DECIMAL(3,1),
    "VIITE" VARCHAR(255),
    "MUOKATTU" VARCHAR(19) NOT NULL,
    "raw_payload_json" TEXT NOT NULL,
    "source_hash" VARCHAR(64),
    "imported_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "legacy_bealt2_pkey" PRIMARY KEY ("REKNO","TAPPA","TAPPV","ERA")
);

-- CreateTable
CREATE TABLE "legacy_bealt3" (
    "REKNO" VARCHAR(20) NOT NULL,
    "TAPPA" VARCHAR(50) NOT NULL,
    "TAPPV" VARCHAR(8) NOT NULL,
    "ERA" SMALLINT NOT NULL,
    "ALKOI" VARCHAR(5),
    "HAKUMIN" SMALLINT,
    "AJOMIN" SMALLINT,
    "HAKU" DECIMAL(6,2),
    "HAUK" DECIMAL(6,2),
    "YVA" DECIMAL(6,2),
    "HLO" DECIMAL(6,2),
    "ALO" DECIMAL(6,2),
    "TJA" DECIMAL(6,2),
    "PIN" DECIMAL(6,2),
    "LT11" CHAR(1),
    "LT12" SMALLINT,
    "LT13" CHAR(1),
    "LT14" CHAR(1),
    "LT15" CHAR(1),
    "LT16" CHAR(1),
    "LT17" VARCHAR(5),
    "LT18" DECIMAL(3,1),
    "LT20" DECIMAL(3,1),
    "LT21" DECIMAL(3,1),
    "LT22" DECIMAL(3,1),
    "LT30" DECIMAL(3,1),
    "LT31" DECIMAL(3,1),
    "LT32" DECIMAL(3,1),
    "LT33" DECIMAL(3,1),
    "LT34" DECIMAL(3,1),
    "LT35" DECIMAL(3,1),
    "LT36" DECIMAL(3,1),
    "LT40" DECIMAL(3,1),
    "LT41" DECIMAL(3,1),
    "LT42" DECIMAL(3,1),
    "LT50" DECIMAL(3,1),
    "LT51" DECIMAL(3,1),
    "LT52" DECIMAL(3,1),
    "LT53" DECIMAL(3,1),
    "LT54" DECIMAL(3,1),
    "LT55" DECIMAL(3,1),
    "LT56" DECIMAL(3,1),
    "LT60" DECIMAL(3,1),
    "LT61" DECIMAL(3,1),
    "VIITE" VARCHAR(255),
    "MUOKATTU" VARCHAR(19) NOT NULL,
    "raw_payload_json" TEXT NOT NULL,
    "source_hash" VARCHAR(64),
    "imported_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "legacy_bealt3_pkey" PRIMARY KEY ("REKNO","TAPPA","TAPPV","ERA")
);

-- CreateIndex
CREATE INDEX "legacy_akoeall_REKNO_idx" ON "legacy_akoeall"("REKNO");
CREATE INDEX "legacy_akoeall_TAPPA_TAPPV_idx" ON "legacy_akoeall"("TAPPA", "TAPPV");
CREATE INDEX "legacy_akoeall_TAPPV_TAPPA_idx" ON "legacy_akoeall"("TAPPV", "TAPPA");
CREATE INDEX "legacy_bealt_REKNO_TAPPA_TAPPV_idx" ON "legacy_bealt"("REKNO", "TAPPA", "TAPPV");
CREATE INDEX "legacy_bealt_TAPPV_TAPPA_idx" ON "legacy_bealt"("TAPPV", "TAPPA");
CREATE INDEX "legacy_bealt0_REKNO_TAPPA_TAPPV_idx" ON "legacy_bealt0"("REKNO", "TAPPA", "TAPPV");
CREATE INDEX "legacy_bealt0_TAPPV_TAPPA_idx" ON "legacy_bealt0"("TAPPV", "TAPPA");
CREATE INDEX "legacy_bealt1_REKNO_TAPPA_TAPPV_idx" ON "legacy_bealt1"("REKNO", "TAPPA", "TAPPV");
CREATE INDEX "legacy_bealt1_TAPPV_TAPPA_idx" ON "legacy_bealt1"("TAPPV", "TAPPA");
CREATE INDEX "legacy_bealt2_REKNO_TAPPA_TAPPV_idx" ON "legacy_bealt2"("REKNO", "TAPPA", "TAPPV");
CREATE INDEX "legacy_bealt2_TAPPV_TAPPA_idx" ON "legacy_bealt2"("TAPPV", "TAPPA");
CREATE INDEX "legacy_bealt3_REKNO_TAPPA_TAPPV_idx" ON "legacy_bealt3"("REKNO", "TAPPA", "TAPPV");
CREATE INDEX "legacy_bealt3_TAPPV_TAPPA_idx" ON "legacy_bealt3"("TAPPV", "TAPPA");
