import { describe, expect, it } from "vitest";

import { mapKoiratietokantaAjokEraWrites } from "../map-ajok-era-writes";

describe("mapKoiratietokantaAjokEraWrites", () => {
  it("maps flat era source fields into runtime era rows", () => {
    const eras = mapKoiratietokantaAjokEraWrites(
      {
        era1Alkoi: "08:10",
        era2Alkoi: null,
        era3Alkoi: null,
        era4Alkoi: null,
        era1HuomautusTeksti: "Ensimmäisen erän huomautus",
        era2HuomautusTeksti: null,
        era3HuomautusTeksti: null,
        era4HuomautusTeksti: null,
        hakuMin1: 12,
        hakuMin2: null,
        hakuMin3: null,
        hakuMin4: null,
        ajoMin1: 31,
        ajoMin2: null,
        ajoMin3: null,
        ajoMin4: null,
        hakuEra1: 7,
        hakuEra2: null,
        hakuEra3: null,
        hakuEra4: null,
        haukkuEra1: 6,
        haukkuEra2: null,
        haukkuEra3: null,
        haukkuEra4: null,
        ajotaitoEra1: 8,
        ajotaitoEra2: null,
        ajotaitoEra3: null,
        ajotaitoEra4: null,
        hakuloysyysTappioEra1: null,
        hakuloysyysTappioEra2: null,
        hakuloysyysTappioEra3: null,
        hakuloysyysTappioEra4: null,
        ajoloysyysTappioEra1: null,
        ajoloysyysTappioEra2: null,
        ajoloysyysTappioEra3: null,
        ajoloysyysTappioEra4: null,
      },
      [
        {
          koodi: "11",
          osa: "",
          nimi: "Paljas maa",
          era1Arvo: "1",
          era2Arvo: "2",
          era3Arvo: null,
          era4Arvo: null,
          jarjestys: 1,
        },
        {
          koodi: "17",
          osa: "",
          nimi: "Lämpötila",
          era1Arvo: "13",
          era2Arvo: null,
          era3Arvo: null,
          era4Arvo: null,
          jarjestys: 7,
        },
      ],
    );

    expect(eras).toEqual([
      {
        era: 1,
        alkoi: "08:10",
        huomautusTeksti: "Ensimmäisen erän huomautus",
        hakumin: 12,
        ajomin: 31,
        haku: 7,
        hauk: 6,
        yva: 8,
        hlo: null,
        alo: null,
        lisatiedot: [
          {
            koodi: "11",
            osa: "",
            nimi: "Paljas maa",
            arvo: "1",
            jarjestys: 1,
          },
          {
            koodi: "17",
            osa: "",
            nimi: "Lämpötila",
            arvo: "13",
            jarjestys: 7,
          },
        ],
      },
      {
        era: 2,
        alkoi: null,
        huomautusTeksti: null,
        hakumin: null,
        ajomin: null,
        haku: null,
        hauk: null,
        yva: null,
        hlo: null,
        alo: null,
        lisatiedot: [
          {
            koodi: "11",
            osa: "",
            nimi: "Paljas maa",
            arvo: "2",
            jarjestys: 1,
          },
        ],
      },
    ]);
  });

  it("skips eras without core data or lisätiedot", () => {
    expect(
      mapKoiratietokantaAjokEraWrites(
        {
          era1Alkoi: null,
          era2Alkoi: null,
          era3Alkoi: null,
          era4Alkoi: null,
          era1HuomautusTeksti: null,
          era2HuomautusTeksti: null,
          era3HuomautusTeksti: null,
          era4HuomautusTeksti: null,
          hakuMin1: null,
          hakuMin2: null,
          hakuMin3: null,
          hakuMin4: null,
          ajoMin1: null,
          ajoMin2: null,
          ajoMin3: null,
          ajoMin4: null,
          hakuEra1: null,
          hakuEra2: null,
          hakuEra3: null,
          hakuEra4: null,
          haukkuEra1: null,
          haukkuEra2: null,
          haukkuEra3: null,
          haukkuEra4: null,
          ajotaitoEra1: null,
          ajotaitoEra2: null,
          ajotaitoEra3: null,
          ajotaitoEra4: null,
          hakuloysyysTappioEra1: null,
          hakuloysyysTappioEra2: null,
          hakuloysyysTappioEra3: null,
          hakuloysyysTappioEra4: null,
          ajoloysyysTappioEra1: null,
          ajoloysyysTappioEra2: null,
          ajoloysyysTappioEra3: null,
          ajoloysyysTappioEra4: null,
        },
        [],
      ),
    ).toEqual([]);
  });

  it("keeps eras that only have per-era huomautus text", () => {
    expect(
      mapKoiratietokantaAjokEraWrites(
        {
          era1Alkoi: null,
          era2Alkoi: null,
          era3Alkoi: null,
          era4Alkoi: null,
          era1HuomautusTeksti: "Haku päättyi tielle.",
          era2HuomautusTeksti: null,
          era3HuomautusTeksti: null,
          era4HuomautusTeksti: null,
          hakuMin1: null,
          hakuMin2: null,
          hakuMin3: null,
          hakuMin4: null,
          ajoMin1: null,
          ajoMin2: null,
          ajoMin3: null,
          ajoMin4: null,
          hakuEra1: null,
          hakuEra2: null,
          hakuEra3: null,
          hakuEra4: null,
          haukkuEra1: null,
          haukkuEra2: null,
          haukkuEra3: null,
          haukkuEra4: null,
          ajotaitoEra1: null,
          ajotaitoEra2: null,
          ajotaitoEra3: null,
          ajotaitoEra4: null,
          hakuloysyysTappioEra1: null,
          hakuloysyysTappioEra2: null,
          hakuloysyysTappioEra3: null,
          hakuloysyysTappioEra4: null,
          ajoloysyysTappioEra1: null,
          ajoloysyysTappioEra2: null,
          ajoloysyysTappioEra3: null,
          ajoloysyysTappioEra4: null,
        },
        [],
      ),
    ).toEqual([
      expect.objectContaining({
        era: 1,
        huomautusTeksti: "Haku päättyi tielle.",
      }),
    ]);
  });
});
